[package]
name = "uwucoin"
version = "0.1.0"
authors = ["legitnull <legitnull0@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.4.3" #rewrite later

[lib]
name = "lib"
path = "src/blockchain/lib.rs"
